### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by scoson09** [LQR471814/FileTransfer#3]
Hi again, it seems the previous error has been resolved so thank you!

However, since the update I'm getting this decode error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\site-packages\FileTransfer\__init__.py", line 38, in worker
    filenameDecoded = filenameDecoded.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 27: invalid start byte

**Comment by LQR471814** [comment]
Sorry for the late response,

Can you provide the filename of the file you're attempting to transfer?
